#!/usr/bin/env python

import sys

from PyQt5.QtWidgets import QApplication

from yplushistogram.gui.window import MainWindow

app = QApplication([])

main = MainWindow()
main.show()

sys.exit(app.exec_())
